server:
  port: 8004


spring:
  application:
    name: cloud-provider-payment
    #模块名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://212.64.34.108:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 212.64.34.108:2181



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gaoyizhe.springcloud.entities    #所有Entity别名类所在包